services:
  - type: web
    name: tablero-insumos
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SQL_PASS
        sync: false
